# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: HamClock"
  org.opencontainers.image.authors: "WBØOEW, Chris Romp NZ6F, linuxct"
  org.opencontainers.image.description: "Adds HamClock to your HomeAssistant."
  org.opencontainers.image.source: "https://github.com/linuxct/hassio-repo"
  org.opencontainers.image.licenses: "GNU Affero GLP 3.0"
args:
  TEMPIO_VERSION: "2021.09.0"
