# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HamClock add-on
version: "0.1"
slug: hamclock
description: HamClock add-on
url: "https://github.com/linuxct/hassio-repo/tree/main/hamclock"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
# options:
#   message: "Hello world..."
schema:
  message: "str?"
# image: "ghcr.io/linuxct/{arch}-addon-hamclock"
