# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HamClock add-on
version: "0.1"
slug: hamclock
description: HamClock add-on
url: "https://github.com/linuxct/hassio-repo/tree/main/hamclock"
arch:
  - amd64
  - aarch64
  - armv7
init: false
map:
  - share:rw
# options:
#   message: "Hello world..."
schema:
  message: "str?"
# image: "ghcr.io/linuxct/{arch}-addon-hamclock"
hassio_api: true
homeassistant_api: true
ingress: true
ingress_port: 8081
ports:
  8080/tcp: null
  8081/tcp: null
ports_description:
  8080/tcp: Management port
  8081/tcp: HamClock Web UI
panel_icon: mdi:radio-tower
panel_title: ADS-B Feeder