# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HamClock add-on
version: "1.0.0"
slug: hamclock
description: Adds HamClock to your Home Assistant
url: "https://github.com/linuxct/hassio-repo/tree/main/hamclock"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
map:
  - share:rw
image: "ghcr.io/linuxct/homeassistant-addon-hamclock-{arch}"
hassio_api: true
homeassistant_api: true
ingress: true
ingress_port: 8081 # On purpose, as we want to be able to visualize the HamClock webui from the dashboard
ingress_entry: "live.html"
#webui: "http://[HOST]:[PORT:8081]/live.html"
ports:
  8080/tcp: null
  8081/tcp: null
ports_description:
  8080/tcp: HamClock management port (expose carefully)
  8081/tcp: HamClock Web UI
panel_icon: mdi:radio-tower
panel_title: HamClock
